siteName: aliyarPoko
productionUrl: https://poko-website-builder-57b.pages.dev
languages:
  - code: fr
    name: fran√ßais
    customUrlPrefix:
      prefix: ''
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
